apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: ${{ secrets.DOCKERHUB_USERNAME }}/supply_chain:order_management
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"  # Assuming your application uses this port
            - name: DB_USER
              value: "${{ secrets.ORDER_DB_USER }}"
            - name: DB_HOST
              value: "${{ secrets.ORDER_DB_HOST }}"
            - name: DB_NAME
              value: "${{ secrets.ORDER_DB_NAME }}"
            - name: DB_PASSWORD
              value: "${{ secrets.ORDER_DB_PASSWORD }}"
            - name: DB_PORT
              value: "${{ secrets.ORDER_DB_PORT }}"
