apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: logistics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      # containers:
      #   - name: order-management
      #     image: ${{ secrets.DOCKERHUB_USERNAME }}/supply_chain:order_management
      #     ports:
      #       - containerPort: 3030
      #     env:
      #       - name: PORT
      #         value: "3030"
      #       - name: DB_USER
      #         value: "${{ secrets.ORDER_DB_USER }}"
      #       - name: DB_HOST
      #         value: "${{ secrets.ORDER_DB_HOST }}"
      #       - name: DB_NAME
      #         value: "${{ secrets.ORDER_DB_NAME }}"
      #       - name: DB_PASSWORD
      #         value: "${{ secrets.ORDER_DB_PASSWORD }}"
      #       - name: DB_PORT
      #         value: "${{ secrets.ORDER_DB_PORT }}"
      containers:
        - name: order-management
          image: "itistopu/supply_chain:order_management"
          ports:
            - containerPort: 3030
          # env:
          #   - name: PORT
          #     value: "${PORT}"
          #   - name: DB_USER
          #     value: "${DB_USER}"
          #   - name: DB_HOST
          #     value: "${DB_HOST}"
          #   - name: DB_NAME
          #     value: "${DB_NAME}"
          #   - name: DB_PASSWORD
          #     value: "${DB_PASSWORD}"
          #   - name: DB_PORT
          #     value: "${DB_PORT}"
          envFrom:
            - configMapRef:
                name: order-management-config
