apiVersion: configuration.konghq.com/v1
kind: KongRoute
metadata:
  name: inventory-management-route
spec:
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  paths:
    - /inventory-management
  service: inventory-management-service
