name: supply_chain_app

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          for service_folder in *_micro/; do
            service_name=$(basename "${service_folder}" "_micro")

            # Check if the local tag exists
            if docker inspect "${{ secrets.DOCKER_USERNAME }}/supply_chain:${service_name}" &> /dev/null; then
              echo "Local tag for ${service_name} exists. Deleting..."
              docker rmi -f "${{ secrets.DOCKER_USERNAME }}/supply_chain:${service_name}"
            fi

            # Build and push Docker image
            docker build -t "${{ secrets.DOCKER_USERNAME }}/supply_chain:${service_name}" "${service_folder}"
            docker push "${{ secrets.DOCKER_USERNAME }}/supply_chain:${service_name}"
          done
